// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1X_AgIX4twkpSm-ZTdL2Vw0JoFNtaVDY',
    appId: '1:273915700208:web:5ef4b0aaf1c2e4ae93f335',
    messagingSenderId: '273915700208',
    projectId: 'expensetrack-8aebd',
    authDomain: 'expensetrack-8aebd.firebaseapp.com',
    storageBucket: 'expensetrack-8aebd.appspot.com',
    measurementId: 'G-DQFTHNX2LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8i1Y1w-BWydoNSHuxZIDGEkNQIO6hfto',
    appId: '1:273915700208:android:bc24132acf63f28493f335',
    messagingSenderId: '273915700208',
    projectId: 'expensetrack-8aebd',
    storageBucket: 'expensetrack-8aebd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Ed2qKvr6dd0dTZj0XXOofcd_Ym_lkAc',
    appId: '1:273915700208:ios:01bbe943efbaaeb693f335',
    messagingSenderId: '273915700208',
    projectId: 'expensetrack-8aebd',
    storageBucket: 'expensetrack-8aebd.appspot.com',
    iosBundleId: 'com.example.expenseTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Ed2qKvr6dd0dTZj0XXOofcd_Ym_lkAc',
    appId: '1:273915700208:ios:01bbe943efbaaeb693f335',
    messagingSenderId: '273915700208',
    projectId: 'expensetrack-8aebd',
    storageBucket: 'expensetrack-8aebd.appspot.com',
    iosBundleId: 'com.example.expenseTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1X_AgIX4twkpSm-ZTdL2Vw0JoFNtaVDY',
    appId: '1:273915700208:web:9db5fd5fa5b338c293f335',
    messagingSenderId: '273915700208',
    projectId: 'expensetrack-8aebd',
    authDomain: 'expensetrack-8aebd.firebaseapp.com',
    storageBucket: 'expensetrack-8aebd.appspot.com',
    measurementId: 'G-V8VZCV5B85',
  );
}
